wandb_version: 1

project:
  desc: null
  value: data-collect
name:
  desc: null
  value: trpo-2f1d-seed0
task:
  desc: null
  value: Gym-Hopper
algo_name:
  desc: null
  value: trpo
group:
  desc: null
  value: Gym-Hopper-seed-0
logdir:
  desc: null
  value: log/trpo-2f1d-seed0/Gym-Hopper-seed-0
env_type:
  desc: null
  value: Gym
agent_type:
  desc: null
  value: Hopper
task_name:
  desc: null
  value: null
task_num:
  desc: null
  value: 1
seed:
  desc: null
  value: 0
num_cores:
  desc: null
  value: null
actor_hidden_dims:
  desc: null
  value:
  - 256
  - 256
hidden_dims:
  desc: null
  value:
  - 256
  - 256
critic_lr:
  desc: null
  value: 0.001
epoch:
  desc: null
  value: 2000
step_per_epoch:
  desc: null
  value: 10
episode_len:
  desc: null
  value: 1000
episode_num:
  desc: null
  value: 2
eval_episodes:
  desc: null
  value: 3
grad_norm:
  desc: null
  value: false
rendering:
  desc: null
  value: false
data_num:
  desc: null
  value: 1000000
import_policy:
  desc: null
  value: false
verbose:
  desc: null
  value: true
device:
  desc: null
  value: cpu
obs_shape:
  desc: null
  value:
  - 11
action_dim:
  desc: null
  value: 3
max_action:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716694795.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 61
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
