wandb_version: 1

project:
  desc: null
  value: purpose
name:
  desc: null
  value: ppo-ad8d-seed0
task:
  desc: null
  value: Gym-InvertedPendulum
algo_name:
  desc: null
  value: ppo
group:
  desc: null
  value: Gym-InvertedPendulum-seed-0
logdir:
  desc: null
  value: log/ppo-ad8d-seed0/Gym-InvertedPendulum-seed-0
env_type:
  desc: null
  value: Gym
agent_type:
  desc: null
  value: InvertedPendulum
task_name:
  desc: null
  value: null
task_num:
  desc: null
  value: 1
seed:
  desc: null
  value: 0
actor_hidden_dims:
  desc: null
  value:
  - 256
  - 256
hidden_dims:
  desc: null
  value:
  - 256
  - 256
K_epochs:
  desc: null
  value: 5
eps_clip:
  desc: null
  value: 0.2
actor_lr:
  desc: null
  value: 0.0001
critic_lr:
  desc: null
  value: 0.001
epoch:
  desc: null
  value: 100
step_per_epoch:
  desc: null
  value: 50
episode_len:
  desc: null
  value: 500
episode_num:
  desc: null
  value: 2
eval_episodes:
  desc: null
  value: 3
rendering:
  desc: null
  value: false
data_num:
  desc: null
  value: 10000
import_policy:
  desc: null
  value: false
verbose:
  desc: null
  value: true
device:
  desc: null
  value: cpu
obs_shape:
  desc: null
  value:
  - 4
action_dim:
  desc: null
  value: 1
max_action:
  desc: null
  value: 3.0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716655256.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
